# Generated by Django 2.2.1 on 2019-08-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ves_struct',
            name='EngRomPos',
            field=models.IntegerField(max_length=4, null=True, verbose_name='机舱位置'),
        ),
        migrations.AlterField(
            model_name='ves_struct',
            name='FotBayNum',
            field=models.IntegerField(max_length=4, null=True, verbose_name='40尺贝位数'),
        ),
        migrations.AlterField(
            model_name='ves_struct',
            name='TweBayNum',
            field=models.IntegerField(max_length=4, null=True, verbose_name='20尺贝位数'),
        ),
    ]
