from django.db import models

# Create your models here.

class Ves_struct(models.Model):
    Vessel = models.CharField(max_length=32, unique=True,verbose_name='船名',null=False)
    VesLeng = models.IntegerField(max_length=4,verbose_name="船长",null=False)
    VesWidth =  models.IntegerField(max_length=4,verbose_name="船宽",null=True)
    VesFrLeng = models.IntegerField(max_length=4,verbose_name="船首长度",null=True)
    TweBayNum = models.IntegerField(max_length=4,verbose_name="20尺贝位数",null=True)
    FotBayNum = models.IntegerField(max_length=4,verbose_name="40尺贝位数",null=True)
    FotBayCom = models.CharField(max_length=64,verbose_name="40组贝",null=True)
    EngRomPos = models.IntegerField(max_length=4,verbose_name="机舱位置",null=True)
    EngRomWid = models.IntegerField(max_length=4,verbose_name="机舱宽度",null=True)
    MidBayDeaWit = models.BooleanField(verbose_name="中间贝处理",null=True)
    RefCtnCap = models.IntegerField(max_length=4,verbose_name="冷冻容量",null=True)
    VesEntBerSpd = models.IntegerField(max_length=4,verbose_name="船舶进港速度",null=True)
    VesBerSpd = models.IntegerField(max_length=4,verbose_name="船舶靠港速度",null=True)
    HigCtnCap = models.IntegerField(max_length=4,verbose_name="高箱容量",null=True)
    CapCtnFotFiv = models.IntegerField(max_length=4,verbose_name="45尺容量",null=True)
    VesEmpGrvHeg = models.IntegerField(max_length=4,verbose_name="空船重心高",null=True)
    VesAtt = models.BooleanField(max_length=2,verbose_name="全隔槽",null=True)
    LoadWeigth = models.IntegerField(max_length=16,verbose_name="载重量",null=True)
    DeckCapWegt = models.IntegerField(max_length=16,verbose_name="甲板容量",null=True)
    CabCap = models.IntegerField(max_length=16,verbose_name="舱内容量",null=True)
    DanCtnAlw = models.BooleanField(max_length=2,verbose_name="允装危险品",null=True)

class Vessel_voy_info(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    ImpVoy = models.CharField(max_length=32, unique=True, verbose_name='进口航次', null=False)
    ExpVoy = models.CharField(max_length=32, verbose_name='出口航次', null=False)
    PlaBerThgTim = models.DateTimeField(verbose_name='计划靠泊时间', null=False)
    PlaUnbThgTim = models.DateTimeField(verbose_name='计划离泊时间', null=False)
    ReaBerThgTim = models.DateTimeField(verbose_name='实际靠泊时间', null=False)
    ActUnbTim = models.DateTimeField(verbose_name='实际离泊时间', null=False)
    PlaBerThgPos = models.IntegerField(max_length=4,verbose_name="计划靠泊位置",null=False)
    ActBerPos = models.IntegerField(max_length=4,verbose_name="实际靠泊位置",null=False)
    BerThgDir = models.CharField(max_length=8, verbose_name='靠泊方向', null=True)
    VesDrauMax = models.IntegerField(max_length=4,verbose_name="进出最大吃水",null=True)
    PlaClosCustTim = models.DateTimeField(verbose_name='计划截关时间', null=True)
    ClosCustTim = models.DateTimeField(verbose_name='截关时间', null=True)
    OpAssSign = models.CharField(max_length=32, verbose_name='已安排作业', null=True)
    EntPlanMakSig = models.CharField(max_length=32, verbose_name='已安排集港', null=True)
    TaskFiniSig = models.CharField(max_length=32, verbose_name='作业完成情况', null=True)
    UnBSta = models.BooleanField(verbose_name='离泊情况', null=True)
    PlaLoaGPCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划进重40",null=True)
    PlaLoaEmpCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划进空40",null=True)
    PlaLoaDraCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划进危40",null=True)
    PlaLoaGPCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进重45",null=True)
    PlaLoaEmpCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进空45",null=True)
    PlaLoaDraCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进危45",null=True)
    PlaUloGPCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划出重40",null=True)
    PlaUloEmpCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划出空40",null=True)
    PlaUloDraCtnFotNum = models.IntegerField(max_length=4,verbose_name="计划出危40",null=True)
    PlaUloGPCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进重45",null=True)
    PlaUloEmpCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进空45",null=True)
    PlaUloDraCtnFotFivNum = models.IntegerField(max_length=4,verbose_name="计划进危45",null=True)


class Ves_bay_lay_struct(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    BayNo = models.CharField(max_length=2, unique=True, verbose_name='贝位', null=False)
    BaySiz = models.IntegerField(max_length=2,  verbose_name='贝尺寸', null=False)
    BayCom = models.CharField(max_length=32, verbose_name='贝组', null=True)
    DeckHeg = models.IntegerField(max_length=4,verbose_name="甲板层高",null=True)
    DeckWidMax = models.IntegerField(max_length=4,verbose_name="甲板最宽",null=True)
    CabHeg = models.IntegerField(max_length=4,verbose_name="舱内层高",null=False)
    CabWidMax = models.IntegerField(max_length=4,verbose_name="舱内最宽",null=False)
    HatCovKind = models.CharField(max_length=32, verbose_name='舱盖板类型', null=False)
    HatCovInfo = models.CharField(max_length=32, verbose_name='舱盖板信息', null=False)

# 层箱位信息
class Ves_slot(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    BayNo = models.CharField(max_length=2, unique=True, verbose_name='贝位', null=False)
    TierNo = models.CharField(max_length=2, unique=True, verbose_name='层号', null=False)
    BaySlot = models.CharField(max_length=32, verbose_name='层箱位', null=False)

# 船箱位信息
class cont_info(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='箱位号', null=False)

# 进口船图
class vessel_map_import(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    Voyage = models.CharField(max_length=32, unique=True, verbose_name='航次', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='箱位号', null=False)
    CtnNo = models.CharField(max_length=32, verbose_name='箱号', null=True)
    CtnTyp = models.CharField(max_length=32,verbose_name='箱型', null=True)
    Size = models.CharField(max_length=2,verbose_name='尺寸', null=True)
    Status = models.CharField(max_length=32,verbose_name='状态', null=True)
    CtnWegt = models.IntegerField(max_length=4,verbose_name='箱重', null=True)
    Owner = models.CharField(max_length=32,verbose_name='持箱人', null=True)
    GForce = models.CharField(max_length=64,verbose_name='货特要求', null=True)
    StaPort = models.CharField(max_length=32,verbose_name='起运港', null=True)
    UnloadPort = models.CharField(max_length=32,verbose_name='卸货港', null=True)
    DesPort = models.CharField(max_length=32,verbose_name='目的港', null=True)
    StrPickAwayCtn = models.BooleanField(verbose_name='直提箱', null=True)
    CtnOpeSta = models.CharField(max_length=32,verbose_name='箱作业状态', null=True)

# 预配船图
class pre_vessel_map(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    Voyage = models.CharField(max_length=32, unique=True, verbose_name='航次', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='计划船箱位', null=False)
    CtnTyp = models.CharField(max_length=32, verbose_name='箱型', null=True)
    Size = models.CharField(max_length=2, verbose_name='尺寸', null=True)
    CtnWegtLev = models.IntegerField(max_length=4, verbose_name='箱重等级', null=True)
    Owner = models.CharField(max_length=32, verbose_name='持箱人', null=True)
    GForce = models.CharField(max_length=64, verbose_name='货特要求', null=True)
    StaPort = models.CharField(max_length=32, verbose_name='起运港', null=True)
    UnloadPort = models.CharField(max_length=32, verbose_name='卸货港', null=True)
    DesPort = models.CharField(max_length=32, verbose_name='目的港', null=True)
    StrPickAwayCtn = models.BooleanField(verbose_name='直提箱', null=True)
    CtnOpeSta = models.CharField(max_length=32, verbose_name='箱作业状态', null=True)

class con_stowage_export(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    Voyage = models.CharField(max_length=32, unique=True, verbose_name='航次', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='计划船箱位', null=False)
    CtnTyp = models.CharField(max_length=32, verbose_name='箱型', null=True)
    CtnNo = models.CharField(max_length=32, verbose_name='箱号', null=True)
    Size = models.CharField(max_length=2, verbose_name='尺寸', null=True)
    CtnWegtLev = models.IntegerField(max_length=4, verbose_name='箱重等级', null=True)
    Owner = models.CharField(max_length=32, verbose_name='持箱人', null=True)
    GForce = models.CharField(max_length=64, verbose_name='货特要求', null=True)
    StaPort = models.CharField(max_length=32, verbose_name='起运港', null=True)
    UnloadPort = models.CharField(max_length=32, verbose_name='卸货港', null=True)
    DesPort = models.CharField(max_length=32, verbose_name='目的港', null=True)
    StrPickAwayCtn = models.BooleanField(verbose_name='直提箱', null=True)
    CtnOpeSta = models.CharField(max_length=32, verbose_name='箱作业状态', null=True)
    YardCel = models.CharField(max_length=6, verbose_name='堆场箱位', null=True)

class loand_unload_task(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    Voyage = models.CharField(max_length=32, unique=True, verbose_name='航次', null=False)
    BayNo = models.CharField(max_length=2, unique=True, verbose_name='贝位', null=False)
    HatCovNoFir =  models.IntegerField(max_length=2, verbose_name='第一块舱盖板序号', null=False)
    HatCovLengFir = models.CharField(max_length=6, verbose_name='第一块舱盖板宽度', null=False)
    DeckLodNumFir = models.IntegerField(max_length=3, verbose_name='第一块舱盖板甲板装', null=False)
    DeckUloNumFir =  models.IntegerField(max_length=3, verbose_name='第一块舱盖板甲板卸', null=False)
    CabLoaNumFir =  models.IntegerField(max_length=3, verbose_name='第一块舱盖板舱内装', null=False)
    CabUloNumFir =  models.IntegerField(max_length=3, verbose_name='第一块舱盖板舱内卸', null=False)
    HatCovNoSec = models.IntegerField(max_length=2, verbose_name='第二块舱盖板序号', null=True)
    HatCovLengSec = models.CharField(max_length=6, verbose_name='第二块舱盖板宽度', null=True)
    DeckLodNumSec = models.IntegerField(max_length=3, verbose_name='第二块舱盖板甲板装', null=True)
    DeckUloNumSec =  models.IntegerField(max_length=3, verbose_name='第二块舱盖板甲板卸', null=True)
    CabLoaNumSec =  models.IntegerField(max_length=3, verbose_name='第二块舱盖板舱内装', null=True)
    CabUloNumSec =  models.IntegerField(max_length=3, verbose_name='第二块舱盖板舱内卸', null=True)
    HatCovNoThr = models.IntegerField(max_length=2, verbose_name='第三块舱盖板序号', null=True)
    HatCovLengThr = models.CharField(max_length=6, verbose_name='第三块舱盖板宽度', null=True)
    DeckLodNumThr = models.IntegerField(max_length=3, verbose_name='第三块舱盖板甲板装', null=True)
    DeckUloNumThr = models.IntegerField(max_length=3, verbose_name='第三块舱盖板甲板卸', null=True)
    CabLoaNumThr = models.IntegerField(max_length=3, verbose_name='第三块舱盖板舱内装', null=True)
    CabUloNumThr = models.IntegerField(max_length=3, verbose_name='第三块舱盖板舱内卸', null=True)
    HatCovNoFor = models.IntegerField(max_length=2, verbose_name='第四块舱盖板序号', null=True)
    HatCovLengFor = models.CharField(max_length=6, verbose_name='第四块舱盖板宽度', null=True)
    DeckLodNumFor = models.IntegerField(max_length=3, verbose_name='第四块舱盖板甲板装', null=True)
    DeckUloNumFor = models.IntegerField(max_length=3, verbose_name='第四块舱盖板甲板卸', null=True)
    CabLoaNumFor = models.IntegerField(max_length=3, verbose_name='第四块舱盖板舱内装', null=True)
    CabUloNumFor = models.IntegerField(max_length=3, verbose_name='第四块舱盖板舱内卸', null=True)

# 箱重等级
class ctnwegt_lev_info(models.Model):
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    Voyage = models.CharField(max_length=32, unique=True, verbose_name='航次', null=False)
    CtnWegtRan = models.CharField(max_length=32, verbose_name='等级范围', null=False)
    CtnWegtLev = models.CharField(max_length=4, unique=True, verbose_name='等级', null=False)


