from django.db import models
from vessel.models import *
# Create your models here.

# 岸桥信息
class quary_info(models.Model):
    QCNo = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥编号")
    Qckind = models.CharField(max_length=2,null=False,verbose_name="岸桥类别")
    QcPos = models.CharField(max_length=4,null=True,verbose_name="岸桥位置")
    QCSta = models.CharField(max_length=8,unique=True,null=False,verbose_name="岸桥状态")
    Voyage = models.CharField(max_length=32, unique=True, null=False, verbose_name='航次')
    BegBayPoi = models.IntegerField(max_length=2,null=True,verbose_name="起贝定位")
    OpBerthPos = models.CharField(max_length=32, null=True, verbose_name='当前作业岸边位置')
    NowOpVesCelFir = models.CharField(max_length=6, null=True, verbose_name='当前作业船箱位一')
    NowOpVesCelSec = models.CharField(max_length=6, null=True, verbose_name='当前作业船箱位二')
    NowOpVesCelThr = models.CharField(max_length=6, null=True, verbose_name='当前作业船箱位三')
    NowOpVesCelFor = models.CharField(max_length=6, null=True, verbose_name='当前作业船箱位四')
    OpCtnNoFir = models.CharField(max_length=16, null=True, verbose_name='当前作业箱号一')
    OpCtnNoSec =  models.CharField(max_length=16, null=True, verbose_name='当前作业箱号二')
    OpCtnNoThr =  models.CharField(max_length=16, null=True, verbose_name='当前作业箱号三')
    OpCtnNoFor =  models.CharField(max_length=16, null=True, verbose_name='当前作业箱号四')
    OpAgvFir =  models.CharField(max_length=16, null=True, verbose_name='当前作业AGV一')
    OpAgvSec =  models.CharField(max_length=16, null=True, verbose_name='当前作业AGV二')
    OpAgvThr =  models.CharField(max_length=16, null=True, verbose_name='当前作业AGV三')
    OpAgvFor =  models.CharField(max_length=16, null=True, verbose_name='当前作业AGV四')
    QcNoLeft =  models.CharField(max_length=2, null=True, verbose_name='左侧岸桥编号')
    QcNoRight =  models.CharField(max_length=2, null=True, verbose_name='右侧岸桥编号')
    VesOPTim = models.DateTimeField(null=True,verbose_name="船上时间")
    AgvTimFir = models.DateTimeField(null=True,verbose_name="AGV第一时间")
    AgvTimSec = models.DateTimeField(null=True,verbose_name="AGV第二时间")
    PlfOpTimFir = models.DateTimeField(null=True,verbose_name="平台第一时间")
    PlfOpTimSec = models.DateTimeField(null=True,verbose_name="平台第二时间")
    PlfOpTimThr = models.DateTimeField(null=True,verbose_name="平台第三时间")
    PlfOpTimFou = models.DateTimeField(null=True,verbose_name="平台第四时间")
    PlaQcMtnFiniTim = models.DateTimeField(null=True,verbose_name="岸桥预计修复时间")

# 岸桥结构类别信息
class qc_struct_info(models.Model):
    Qckind = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥类别")
    QcLengFr = models.IntegerField(max_length=3,null=True,verbose_name="外伸距")
    QcOpLengFr = models.IntegerField(max_length=3,null=True,verbose_name="外伸作业距")
    QcHeg = models.IntegerField(max_length=3,null=True,verbose_name="岸桥高度")
    OpHeg = models.IntegerField(max_length=3,null=True,verbose_name="作业高度")
    QcLengTr = models.IntegerField(max_length=3,null=True,verbose_name="后伸距")
    OpLengTr = models.IntegerField(max_length=3,null=True,verbose_name="后伸作业距")
    PlfPos = models.IntegerField(max_length=3,null=True,verbose_name="平台位置")
    BetLegLeng = models.IntegerField(max_length=3,null=True,verbose_name="大车跨道跨距")
    BetLegLanNum = models.IntegerField(max_length=3,null=True,verbose_name="大车跨下车道数")
    LifSpdDolFr = models.IntegerField(max_length=3,null=True,verbose_name="前置小车起升速度")
    DowVelDolFro = models.IntegerField(max_length=3,null=True,verbose_name="前置小车下降速度")
    HorSpdDolFr = models.IntegerField(max_length=3,null=True,verbose_name="前置小车水平速度")
    OpStyDolFro = models.IntegerField(max_length=3,null=True,verbose_name="前置小车作业方式")
    LifSpdDolTr = models.IntegerField(max_length=3,null=True,verbose_name="后置小车起升速度")
    DowVelDolTr = models.IntegerField(max_length=3,null=True,verbose_name="后置小车下降速度")
    HorSpdDolTr = models.IntegerField(max_length=3,null=True,verbose_name="后置小车水平速度")
    OpKindDolTr = models.IntegerField(max_length=3,null=True,verbose_name="后置小车作业方式")

class qc_load_task(models.Model):
    QCNo = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥编号")
    ImpVoy = models.CharField(max_length=32, unique=True, verbose_name='进口航次', null=False)
    ExpVoy = models.CharField(max_length=32, verbose_name='出口航次', null=False)
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='箱位号', null=False)

class qc_unload_task(models.Model):
    QCNo = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥编号")
    ImpVoy = models.CharField(max_length=32, unique=True, verbose_name='进口航次', null=False)
    ExpVoy = models.CharField(max_length=32, verbose_name='出口航次', null=False)
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    VesCellNo = models.CharField(max_length=6, unique=True, verbose_name='箱位号', null=False)

class qc_work_plan(models.Model):
    QCNo = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥编号")
    Vessel = models.CharField(max_length=32, unique=True, verbose_name='船名', null=False)
    ImpVoy = models.CharField(max_length=32, unique=True, verbose_name='进口航次', null=False)
    ExpVoy = models.CharField(max_length=32, verbose_name='出口航次', null=False)
    OpBay = models.CharField(max_length=2, verbose_name='作业贝位', null=False)
    BayBlockNo = models.CharField(max_length=10, verbose_name='贝位内作业块编号', null=True)
    OpKind = models.CharField(max_length=4, verbose_name='作业类别', null=True)
    OpPos = models.CharField(max_length=32, verbose_name='作业位置', null=True)
    PreOpVes = models.CharField(max_length=32, unique=True, verbose_name='紧前作业船舶', null=True)
    preImpVoy = models.CharField(max_length=32, unique=True, verbose_name='紧前作业进口航次', null=True)
    PreOpBay = models.CharField(max_length=2, verbose_name='紧前作业贝位', null=True)
    PreBayBlockNo = models.CharField(max_length=10, verbose_name='紧前贝位内作业块编号', null=True)
    PreOpPos = models.CharField(max_length=32, verbose_name='紧前作业位置', null=True)
    PreOpKind = models.CharField(max_length=4, verbose_name='紧前作业类别', null=True)

class qc_workbay_plan(models.Model):
    QCNo = models.CharField(max_length=2,unique=True,null=False,verbose_name="岸桥编号")
    OpSta = models.CharField(max_length=8,null=True,verbose_name="作业状态")
    ImpVoy = models.CharField(max_length=32, unique=True, verbose_name='进口航次', null=False)
    ExpVoy = models.CharField(max_length=32, verbose_name='出口航次', null=False)
    OpVes = models.CharField(max_length=32, unique=True, verbose_name='作业船舶', null=False)
    OpBay = models.CharField(max_length=2, verbose_name='作业贝位', null=False)
    BayBlockNo = models.CharField(max_length=10, verbose_name='贝位内作业块编号', null=True)
    OpKind = models.CharField(max_length=4, verbose_name='作业类别', null=True)
    NowOpVesCelFir = models.CharField(max_length=6, unique=True, verbose_name='当前作业船箱位一', null=False)
    CtnNoFir = models.CharField(max_length=16, verbose_name='箱号一', null=False)
    CtnSizFir = models.CharField(max_length=6,verbose_name='箱号一尺寸', null=False)
    BerPosFir = models.CharField(max_length=4, verbose_name='岸边位一', null=True)
    NowOpVesCelSec = models.CharField(max_length=6,verbose_name='当前作业船箱位二', null=True)
    CtnNoSec = models.CharField(max_length=16, verbose_name='箱号二', null=False)
    CtnSizSec = models.CharField(max_length=6,verbose_name='箱号二尺寸', null=False)
    BerPosSec = models.CharField(max_length=4, verbose_name='岸边位二', null=True)
    NowOpVesCelThr = models.CharField(max_length=6,verbose_name='当前作业船箱位三', null=True)
    CtnNoThr = models.CharField(max_length=16, verbose_name='箱号三', null=False)
    CtnSizThr = models.CharField(max_length=6,verbose_name='箱号三尺寸', null=False)
    BerPosThr = models.CharField(max_length=4, verbose_name='岸边位三', null=True)
    NowOpVesCelFou = models.CharField(max_length=6,verbose_name='当前作业船箱位四', null=True)
    CtnNoFou = models.CharField(max_length=16, verbose_name='箱号四', null=True)
    CtnSizFou = models.CharField(max_length=6,verbose_name='箱号四尺寸', null=True)
    BerPosFou = models.CharField(max_length=4, verbose_name='岸边位四', null=True)
    PreVesCelFir = models.CharField(max_length=6, verbose_name='紧前作业船箱位一', null=True)
    PreVesCelSec = models.CharField(max_length=6, verbose_name='紧前作业船箱位二', null=True)
    PreVesCelThr = models.CharField(max_length=6, verbose_name='紧前作业船箱位三', null=True)
    PreVesCelFou = models.CharField(max_length=6, verbose_name='紧前作业船箱位四', null=True)

    PreOpCtnNoFir = models.CharField(max_length=16, null=True, verbose_name='紧前作业箱号一')
    PreOpCtnNoSec = models.CharField(max_length=16, null=True, verbose_name='紧前作业箱号二')
    PreOpCtnNoThr = models.CharField(max_length=16, null=True, verbose_name='紧前作业箱号三')
    PreOpCtnNoFor = models.CharField(max_length=16, null=True, verbose_name='紧前作业箱号四')

    PreOpVes = models.CharField(max_length=32, unique=True, verbose_name='紧前作业船舶', null=True)
    PreOpBay = models.CharField(max_length=2, verbose_name='紧前作业贝位', null=True)
    NowOpBay = models.CharField(max_length=2, verbose_name='当前作业贝位', null=True)
    DesBay = models.CharField(max_length=2, verbose_name='目标贝位', null=True)

